version: "3"

services:
  db:
    image: mongo:6.0.12
    restart: "always"
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
  api:
    build: ./backend
    restart: "unless-stopped"
    ports:
      - "5000:5000"
      - "9229:9229"
    environment:
      MONGO_URI: "mongodb://root:password@db:27017/challengeDB?authSource=admin"
    depends_on:
      - db
    tty: true
    container_name: backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    command: npm run start:debug
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    command: npm run dev
volumes:
  mongo-data:
